[project]
name = "test"
version = "0.0.1"
description = ""
author = ""

[vectordb]
name = "embeddings"
inRepoPath = "./data"
branchName = "dev"
sourceBranch = "main"
commitHash = "b6ba014d87cd8a382560c7d37964496726663e79d085a4740593457027684022"

[project.dependencies]
