version: "3"
vars:
  CONTAINER_NAME: "lmorbits-obeservation"
  IMAGE_NAME: "arizephoenix/phoenix:latest"
tasks:
  start:
    vars:
      PORT: "{{.PORT | default 6006}}"
      GRPC_PORT: "{{.GRPC_PORT | default 4317}}"
    cmds:
      - |
        if [ "$(docker ps -q --filter "status=exited" -f name={{.CONTAINER_NAME}})" ]; then
          docker start {{.CONTAINER_NAME}}
        else
          container_id=$(docker run -d \
            --name {{.CONTAINER_NAME}} \
            -p {{.PORT}}:6006 \
            -p {{.GRPC_PORT}}:4317 \
            {{.IMAGE_NAME}})
        fi

  stop:
    cmds:
      - |
        if [ "$(docker ps -q -f name={{.CONTAINER_NAME}} | wc -l)" -gt 0 ]; then
          docker stop $(docker ps -q -f name={{.CONTAINER_NAME}})
        fi

  remove:
    cmds:
      - |
        if [ "$(docker ps -q -f name={{.CONTAINER_NAME}})" ]; then
             docker stop $(docker ps -q -f name={{.CONTAINER_NAME}})
             
           fi
           docker rm $(docker ps -aq -f name={{.CONTAINER_NAME}})

  status:
    cmds:
      - "docker ps | grep {{.CONTAINER_NAME}} | wc -l"
