[project]
name = "pyapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "parsa", email = "parsa.miraghaie@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "go-task-bin>=3.43.3",
    "loguru>=0.7.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pyapp"]

[project.optional-dependencies]
local = ["local"]

[dependency-groups]
local = [
  "arize-phoenix-otel>=0.9.2",
  "openinference-instrumentation-langchain>=0.1.42",
]
